## Crypto Coins Selected: 
- Bitcoin, Ethereum, Solana, Dogecoin, Tether

In [44]:
import requests
import pandas as pd
import os 
from dotenv import load_dotenv
from sqlalchemy import create_engine

load_dotenv()

url = "https://api.coinpaprika.com/v1/tickers?quotes=USD"

response = requests.get(url)

print(response.text)

response.json()

[{"id":"btc-bitcoin","name":"Bitcoin","symbol":"BTC","rank":1,"total_supply":20052166,"max_supply":21000000,"beta_value":0.971691,"first_data_at":"2010-07-17T00:00:00Z","last_updated":"2026-07-04T20:43:15Z","quotes":{"USD":{"price":63196.947775148765,"volume_24h":16790265688.53894,"volume_24h_change_24h":-26.690000534057617,"market_cap":1267235687480,"market_cap_change_24h":1.149999976158142,"percent_change_15m":0.07999999821186066,"percent_change_30m":-0.10999999940395355,"percent_change_1h":-0.07999999821186066,"percent_change_6h":0.9399999976158142,"percent_change_12h":1.0800000429153442,"percent_change_24h":1.149999976158142,"percent_change_7d":4.989999771118164,"percent_change_30d":0,"percent_change_1y":0,"ath_price":126173.1777846797,"ath_date":"2025-10-06T19:00:40Z","percent_from_price_ath":-49.91}}},{"id":"eth-ethereum","name":"Ethereum","symbol":"ETH","rank":2,"total_supply":120232214,"max_supply":0,"beta_value":1.45069,"first_data_at":"2015-08-07T00:00:00Z","last_updated":"2026-07-04T20:43:15Z","quotes":{"USD":{"price":1787.3090327303148,"volume_24h":5781206580.846204,"volume_24h_change_24h":-18.729999542236328,"market_cap":215239042365,"market_cap_change_24h":1.7599999904632568,"percent_change_15m":0.14000000059604645,"percent_change_30m":-0.27000001072883606,"percent_change_1h":-0.27000001072883606,"percent_change_6h":1.0499999523162842,"percent_change_12h":1.5499999523162842,"percent_change_24h":1.7599999904632568,"percent_change_7d":13.329999923706055,"percent_change_30d":0,"percent_change_1y":0,"ath_price":4946.229669645212,"ath_date":"2025-08-24T19:24:38Z","percent_from_price_ath":-63.88}}},{"id":"usdt-tether","name":"Tether","symbol":"USDT","rank":3,"total_supply":189750324523,"max_supply":0,"beta_value":-0.00149119,"first_data_at":"2015-02-25T00:00:00Z","last_updated":"2026-07-04T20:43:15Z","quotes":{"USD":{"price":0.9991413186529158,"volume_24h":31598672580.20061,"volume_24h_change_24h":-28.739999771118164,"market_cap":184125142085,"market_cap_change_24h":0.019999999552965164,"percent_change_15m":-0.009999999776482582,"percent_change_30m":0,"percent_change_1h":0.009999999776482582,"percent_change_6h":0,"percent_change_12h":0.019999999552965164,"percent_change_24h":0.019999999552965164,"percent_change_7d":0.07000000029802322,"percent_change_30d":0,"percent_change_1y":0,"ath_price":1.21549,"ath_date":"2015-02-25T17:04:00Z","percent_from_price_ath":-17.8}}},{"id":"bnb-binance-coin","name":"BNB","symbol":"BNB","rank":4,"total_supply":134782677,"max_supply":200000000,"beta_value":1.04891,"first_data_at":"2017-07-25T00:00:00Z","last_updated":"2026-07-04T20:43:15Z","quotes":{"USD":{"price":573.3980385824108,"volume_24h":480878248.742317,"volume_24h_change_24h":-2.430000066757202,"market_cap":77284122626,"market_cap_change_24h":0.3100000023841858,"percent_change_15m":0.05999999865889549,"percent_change_30m":-0.23000000417232513,"percent_change_1h":-0.36000001430511475,"percent_change_6h":-0.10000000149011612,"percent_change_12h":-0.25,"percent_change_24h":0.3100000023841858,"percent_change_7d":2.5999999046325684,"percent_change_30d":0,"percent_change_1y":0,"ath_price":1370.9838437844724,"ath_date":"2025-10-13T09:00:44Z","percent_from_price_ath":-58.19}}},{"id":"usdc-usd-coin","name":"USDC","symbol":"USDC","rank":5,"total_supply":72962441353,"max_supply":0,"beta_value":-0.00346838,"first_data_at":"2018-10-09T00:00:00Z","last_updated":"2026-07-04T20:43:15Z","quotes":{"USD":{"price":0.9998783832352426,"volume_24h":7974366347.905231,"volume_24h_change_24h":-26.530000686645508,"market_cap":72956117718,"market_cap_change_24h":-0.07000000029802322,"percent_change_15m":-0.009999999776482582,"percent_change_30m":0,"percent_change_1h":0.009999999776482582,"percent_change_6h":0.009999999776482582,"percent_change_12h":0.009999999776482582,"percent_change_24h":0,"percent_change_7d":0.009999999776482582,"percent_change_30d":0,"percent_change_1y":0,"ath_price":1.90619801,"ath_date":"2018-10-11T06:35:00Z","percent_from_price_ath":-47.55}}},{"id":"xrp-xrp","name":"XRP","symbol":"XRP","rank":6,"total_supply":99985645029,"max_supply":100000000000,"beta_value":1.31707,"first_data_at":"2013-08-04T00:00:00Z","last_updated":"2026-07-04T20:43:15Z","quotes":{"USD":{"price":1.161274713674448,"volume_24h":1465750084.5322864,"volume_24h_change_24h":8.550000190734863,"market_cap":72279490316,"market_cap_change_24h":2.990000009536743,"percent_change_15m":0.07999999821186066,"percent_change_30m":-0.5699999928474426,"percent_change_1h":-0.49000000953674316,"percent_change_6h":-0.9700000286102295,"percent_change_12h":1.8300000429153442,"percent_change_24h":2.990000009536743,"percent_change_7d":10.399999618530273,"percent_change_30d":0,"percent_change_1y":0,"ath_price":3.84194,"ath_date":"2018-01-04T07:14:00Z","percent_from_price_ath":-69.77}}},{"id":"sol-solana","name":"Solana","symbol":"SOL","rank":7,"total_supply":588682058,"max_supply":0,"beta_value":1.55129,"first_data_at":"2020-08-26T00:00:00Z","last_updated":"2026-07-04T20:43:15Z","quotes":{"USD":{"price":81.91409385643679,"volume_24h":1605366587.2155302,"volume_24h_change_24h":-2.680000066757202,"market_cap":47602784954,"market_cap_change_24h":-0.33000001311302185,"percent_change_15m":0.18000000715255737,"percent_change_30m":0.05999999865889549,"percent_change_1h":0.17000000178813934,"percent_change_6h":0.2800000011920929,"percent_change_12h":-0.3400000035762787,"percent_change_24h":-0.3499999940395355,"percent_change_7d":15.270000457763672,"percent_change_30d":0,"percent_change_1y":0,"ath_price":294.1631972172844,"ath_date":"2025-01-19T11:17:03Z","percent_from_price_ath":-72.17}}},{"id":"trx-tron","name":"TRON","symbol":"TRX","rank":8,"total_supply":86363124686,"max_supply":0,"beta_value":0.311245,"first_data_at":"2017-09-13T00:00:00Z","last_updated":"2026-07-04T20:43:15Z","quotes":{"USD":{"price":0.3259258382726382,"volume_24h":340645039.3076443,"volume_24h_change_24h":-14.319999694824219,"market_cap":28148030460,"market_cap_change_24h":1.1200000047683716,"percent_change_15m":0.03999999910593033,"percent_change_30m":-0.03999999910593033,"percent_change_1h":-0.009999999776482582,"percent_change_6h":0.1899999976158142,"percent_change_12h":0.6899999976158142,"percent_change_24h":1.1200000047683716,"percent_change_7d":1.6399999856948853,"percent_change_30d":0,"percent_change_1y":0,"ath_price":0.4404408234447792,"ath_date":"2024-12-04T00:12:23Z","percent_from_price_ath":-26.02}}},{"id":"hype-hyperliquid","name":"Hyperliquid","symbol":"HYPE","rank":9,"total_supply":999993930,"max_supply":1000000000,"beta_value":1.3612,"first_data_at":"2024-12-09T00:00:00Z","last_updated":"2026-07-04T20:43:15Z","quotes":{"USD":{"price":69.85829703806039,"volume_24h":197517856.27465457,"volume_24h_change_24h":-30.219999313354492,"market_cap":23327653987,"market_cap_change_24h":-0.9800000190734863,"percent_change_15m":0.27000001072883606,"percent_change_30m":0.18000000715255737,"percent_change_1h":0.11999999731779099,"percent_change_6h":-0.8999999761581421,"percent_change_12h":-1.690000057220459,"percent_change_24h":-0.9800000190734863,"percent_change_7d":12.149999618530273,"percent_change_30d":0,"percent_change_1y":0,"ath_price":76.76282696217518,"ath_date":"2026-06-16T13:01:19Z","percent_from_price_ath":-8.98}}},{"id":"steth-lido-staked-ether","name":"Lido Staked Ether","symbol":"STETH","rank":10,"total_supply":9785853,"max_supply":0,"beta_value":1.45109,"first_data_at":"2021-08-12T00:00:00Z","last_updated":"2026-07-04T20:43:15Z","quotes":{"USD":{"price":1791.421516529502,"volume_24h":6364220.973839704,"volume_24h_change_24h":28.34000015258789,"market_cap":17545897110,"market_cap_change_24h":2.009999990463257,"percent_change_15m":0.11999999731779099,"percent_change_30m":-0.23999999463558197,"percent_change_1h":-0.03999999910593033,"percent_change_6h":1.5099999904632568,"percent_change_12h":1.7699999809265137,"percent_change_24h":2.009999990463257,"percent_change_7d":13.9399995803833,"percent_change_30d":0,"percent_change_1y":0,"ath_price":4930.286952501686,"ath_date":"2025-08-24T19:24:38Z","percent_from_price_ath":-63.69}}},{"id":"doge-dogecoin","name":"Dogecoin","symbol":"DOGE","rank":11,"total_supply":148311776384,"max_supply":0,"beta_value":1.55622,"first_data_at":"2013-12-15T00:00:00Z","last_updated":"2026-07-04T20:43:15Z","quotes":{"USD":{"price":0.07806102619831293,"volume_24h":512395120.5053966,"volume_24h_change_24h":-3.609999895095825,"market_cap":11642622234,"market_cap_change_24h":0.6600000262260437,"percent_change_15m":0.05999999865889549,"percent_change_30m":-0.5799999833106995,"percent_change_1h":-0.6100000143051147,"percent_change_6h":0.7400000095367432,"percent_change_12h":1.5700000524520874,"percent_change_24h":0.6600000262260437,"percent_change_7d":4.760000228881836,"percent_change_30d":0,"percent_change_1y":0,"ath_price":0.75287027,"ath_date":"2021-05-08T05:00:00Z","percent_from_price_ath":-89.63}}},{"id":"usds-usds","name":"Usds","symbol":"USDS","rank":12,"total_supply":11077194156,"max_supply":0,"beta_value":-0.0040967,"first_data_at":"2024-09-21T00:00:00Z","last_updated":"2026-07-04T20:43:15Z","quotes":{"USD":{"price":0.9997782844308519,"volume_24h":53950131.90850474,"volume_24h_change_24h":-52.09000015258789,"market_cap":11074738169,"market_cap_change_24h":0,"percent_change_15m":-0,"percent_change_30m":0.009999999776482582,"percent_change_1h":0.009999999776482582,"percent_change_6h":-0,"percent_change_12h":0.009999999776482582,"percent_change_24h":0,"percent_change_7d":0.03999999910593033,"percent_change_30d":0,"percent_change_1y":0,"ath_price":1.5820505120750166,"ath_date":"2024-09-24T03:00:21Z","percent_from_price_ath":-36.8}}},{"id":"leo-leo-token","name":"LEO Token","symbol":"LEO","rank":13,"total_supply":985239504,"max_supply":0,"beta_value":0.255359,"first_data_at":"2019-05-20T00:00:00Z","last_updated":"2026-07-04T20:43:15Z","quotes":{"USD":{"price":9.143799108706803,"volume_24h":87923.61185242282,"volume_24h_change_24h":-70.20999908447266,"market_cap":8420333795,"market_cap_change_24h":-0.14000000059604645,"percent_change_15m":-0.07000000029802322,"percent_change_30m":0.019999999552965164,"percent_change_1h":-0.019999999552965164,"percent_change_6h":-0.20000000298023224,"percent_change_12h":-0.20999999344348907,"percent_change_24h":-0.14000000059604645,"percent_change_7d":-2.890000104904175,"percent_change_30d":0,"percent_change_1y":0,"ath_price":10.45821201979332,"ath_date":"2026-04-29T01:22:16Z","percent_from_price_ath":-12.52}}},{"id":"wbtc-wrapped-bitcoin","name":"Wrapped Bitcoin","symbol":"WBTC","rank":14,"total_supply":131178,"max_supply":0,"beta_value":0.970677,"first_data_at":"2019-01-31T00:00:00Z","last_updated":"2026-07-04T20:43:15Z","quotes":{"USD":{"price":63191.49267025023,"volume_24h":118424058.01568425,"volume_24h_change_24h":-10.15999984741211,"market_cap":8289333625,"market_cap_change_24h":1.1799999475479126,"percent_change_15m":0.09000000357627869,"percent_change_30m":-0.10999999940395355,"percent_change_1h":-0.05999999865889549,"percent_change_6h":0.949999988079071,"percent_change_12h":1.090000033378601,"percent_change_24h":1.1799999475479126,"percent_change_7d":5.110000133514404,"percent_change_30d":0,"percent_change_1y":0,"ath_price":126028.39561559023,"ath_date":"2025-10-06T19:03:39Z","percent_from_price_ath":-49.87}}},{"id":"wbt-whitebit","name":"WhiteBIT Coin","symbol":"WBT","rank":15,"total_supply":369441188,"max_supply":400000000,"beta_value":0.706237,"first_data_at":"2022-08-26T00:00:00Z","last_updated":"2026-07-04T20:43:15Z","quotes":{"USD":{"price":57.041114180341125,"volume_24h":75666316.02673513,"volume_24h_change_24h":-19.34000015258789,"market_cap":8220680783,"market_cap_change_24h":0.9599999785423279,"percent_change_15m":0.10999999940395355,"percent_change_30m":-0.14000000059604645,"percent_change_1h":-0.11999999731779099,"percent_change_6h":0.8700000047683716,"percent_change_12h":0.9100000262260437,"percent_change_24h":0.9599999785423279,"percent_change_7d":18.739999771118164,"percent_change_30d":0,"percent_change_1y":0,"ath_price":64.48298634623086,"ath_date":"2025-12-10T20:19:16Z","percent_from_price_ath":-11.54}}},{"id":"wsteth-wrapped-liquid-staked-ether-20","name":"Wrapped Liquid Staked Ether 2.0","symbol":"WSTETH","rank":16,"total_supply":3555731,"max_supply":0,"beta_value":1.45128,"first_data_at":"2022-06-08T00:00:00Z","last_updated":"2026-07-04T20:43:15Z","quotes":{"USD":{"price":2212.5046183834884,"volume_24h":3701477.5556296236,"volume_24h_change_24h":-8.829999923706055,"market_cap":7867071259,"market_cap_change_24h":1.7699999809265137,"percent_change_15m":0.10000000149011612,"percent_change_30m":-0.3199999928474426,"percent_change_1h":-0.28999999165534973,"percent_change_6h":1.059999942779541,"percent_change_12h":1.6200000047683716,"percent_change_24h":1.7699999809265137,"percent_change_7d":13.34000015258789,"percent_change_30d":0,"percent_change_1y":0,"ath_price":5979.080126100078,"ath_date":"2025-08-24T19:24:38Z","percent_from_price_ath":-63}}},{"id":"zec-zcash","name":"Zcash","symbol":"ZEC","rank":17,"total_supply":16328269,"max_supply":21000000,"beta_value":1.7072,"first_data_at":"2016-10-29T00:00:00Z","last_updated":"2026-07-04T20:43:15Z","quotes":{"USD":{"price":467.6266605898083,"volume_24h":234849429.54142475,"volume_24h_change_24h":-42.130001068115234,"market_cap":7635533905,"market_cap_change_24h":0.8399999737739563,"percent_change_15m":0.3400000035762787,"percent_change_30m":-0.09000000357627869,"percent_change_1h":-0.28999999165534973,"percent_change_6h":0.6499999761581421,"percent_change_12h":1.5299999713897705,"percent_change_24h":0.8399999737739563,"percent_change_7d":17.399999618530273,"percent_change_30d":0,"percent_change_1y":0,"ath_price":5941.8,"ath_date":"2016-10-29T15:59:00Z","percent_from_price_ath":-92.12}}},{"id":"ada-cardano","name":"Cardano","symbol":"ADA","rank":18,"total_supply":44995037804,"max_supply":45000000000,"beta_value":1.63183,"first_data_at":"2017-10-01T00:00:00Z","last_updated":"2026-07-04T20:43:15Z","quotes":{"USD":{"price":0.1915808223313957,"volume_24h":664007287.2587409,"volume_24h_change_24h":7.699999809265137,"market_cap":7420584893,"market_cap_change_24h":7.230000019073486,"percent_change_15m":-0.009999999776482582,"percent_change_30m":-0.800000011920929,"percent_change_1h":-0.7900000214576721,"percent_change_6h":5.019999980926514,"percent_change_12h":8.930000305175781,"percent_change_24h":7.199999809265137,"percent_change_7d":32.34000015258789,"percent_change_30d":0,"percent_change_1y":0,"ath_price":3.0950278974839334,"ath_date":"2021-09-02T06:00:00Z","percent_from_price_ath":-93.81}}},{"id":"xlm-stellar","name":"Stellar","symbol":"XLM","rank":19,"total_supply":50001786840,"max_supply":50001806812,"beta_value":1.34376,"first_data_at":"2014-08-05T00:00:00Z","last_updated":"2026-07-04T20:43:15Z","quotes":{"USD":{"price":0.20855426484176284,"volume_24h":668331279.6701117,"volume_24h_change_24h":188.5399932861328,"market_cap":7089327682,"market_cap_change_24h":2.319999933242798,"percent_change_15m":-0.009999999776482582,"percent_change_30m":-0.3799999952316284,"percent_change_1h":-0.5,"percent_change_6h":1.3700000047683716,"percent_change_12h":0.9300000071525574,"percent_change_24h":2.319999933242798,"percent_change_7d":19.799999237060547,"percent_change_30d":0,"percent_change_1y":0,"ath_price":0.938144,"ath_date":"2018-01-04T08:19:00Z","percent_from_price_ath":-77.74}}},{"id":"weth-weth","name":"WETH","symbol":"WETH","rank":20,"total_supply":3765896,"max_supply":0,"beta_value":1.44979,"first_data_at":"2018-01-14T00:00:00Z","last_updated":"2026-07-04T20:43:15Z","quotes":{"USD":{"price":1786.551411006403,"volume_24h":266220347.7730071,"volume_24h_change_24h":6.230000019073486,"market_cap":6727966812,"market_cap_change_24h":1.7000000476837158,"percent_change_15m":0.10000000149011612,"percent_change_30m":-0.3199999928474426,"percent_change_1h":-0.3199999928474426,"percent_change_6h":1,"percent_change_12h":1.5199999809265137,"percent_change_24h":1.7000000476837158,"percent_change_7d":13.300000190734863,"percent_change_30d":0,"percent_change_1y":0,"ath_price":4944.739160754335,"ath_date":"2025-08-24T19:24:38Z","percent_from_price_ath":-63.91}}},{"id":"xmr-monero","name":"Monero","symbol":"XMR","rank":21,"total_supply":18773624,"max_supply":0,"beta_value":0.836937,"first_data_at":"2014-05-21T00:00:00Z","last_updated":"2026-07-04T20:43:15Z","quotes":{"USD":{"price":328.64792105104965,"volume_24h":164281516.77758306,"volume_24h_change_24h":20.280000686645508,"market_cap":6169912169,"market_cap_change_24h":1.440000057220459,"percent_change_15m":0.15000000596046448,"percent_change_30m":0.2800000011920929,"percent_change_1h":-0.07000000029802322,"percent_change_6h":-1.090000033378601,"percent_change_12h":-0.8500000238418579,"percent_change_24h":1.4299999475479126,"percent_change_7d":5.380000114440918,"percent_change_30d":0,"percent_change_1y":0,"ath_price":797.1378386984193,"ath_date":"2026-01-14T19:34:17Z","percent_from_price_ath":-58.76}}},{"id":"usde-ethena-usde","name":"Ethena USDe","symbol":"USDE","rank":22,"total_supply":5419558970,"max_supply":0,"beta_value":-0.000736692,"first_data_at":"2023-12-20T00:00:00Z","last_updated":"2026-07-04T20:43:15Z","quotes":{"USD":{"price":0.9985918870164702,"volume_24h":27803440.44107519,"volume_24h_change_24h":-60.869998931884766,"market_cap":5411927618,"market_cap_change_24h":0.009999999776482582,"percent_change_15m":-0,"percent_change_30m":0,"percent_change_1h":0.009999999776482582,"percent_change_6h":-0.019999999552965164,"percent_change_12h":-0.009999999776482582,"percent_change_24h":0.009999999776482582,"percent_change_7d":0.05000000074505806,"percent_change_30d":0,"percent_change_1y":0,"ath_price":12.7108250395207,"ath_date":"2024-01-20T07:41:01Z","percent_from_price_ath":-92.14}}},{"id":"rain-rain-protocol","name":"Rain Protocol","symbol":"RAIN","rank":23,"total_supply":1149948563353,"max_supply":1149996077984,"beta_value":0.146182,"first_data_at":"2026-01-20T00:00:00Z","last_updated":"2026-07-04T20:43:15Z","quotes":{"USD":{"price":0.01541338672691332,"volume_24h":8875745.002458367,"volume_24h_change_24h":-0.07000000029802322,"market_cap":5236301236,"market_cap_change_24h":-0.3700000047683716,"percent_change_15m":0.09000000357627869,"percent_change_30m":-0.05000000074505806,"percent_change_1h":-0.05000000074505806,"percent_change_6h":-0.17000000178813934,"percent_change_12h":-0.3700000047683716,"percent_change_24h":-0.3700000047683716,"percent_change_7d":-0.9300000071525574,"percent_change_30d":0,"percent_change_1y":0,"ath_price":0.016165617061481518,"ath_date":"2026-06-24T11:52:17Z","percent_from_price_ath":-4.7}}},{"id":"weeth-wrapped-eeth","name":"Wrapped eETH","symbol":"WEETH","rank":24,"total_supply":2621497,"max_supply":0,"beta_value":1.45161,"first_data_at":"2024-03-02T00:00:00Z","last_updated":"2026-07-04T20:43:15Z","quotes":{"USD":{"price":1961.7112094059298,"volume_24h":645171.2800061062,"volume_24h_change_24h":-75.36000061035156,"market_cap":5142620050,"market_cap_change_24h":1.7300000190734863,"percent_change_15m":0.10999999940395355,"percent_change_30m":-0.3199999928474426,"percent_change_1h":-0.3100000023841858,"percent_change_6h":1.0099999904632568,"percent_change_12h":1.5199999809265137,"percent_change_24h":1.7300000190734863,"percent_change_7d":13.359999656677246,"percent_change_30d":0,"percent_change_1y":0,"ath_price":5297.876991948052,"ath_date":"2025-08-24T19:15:38Z","percent_from_price_ath":-63}}},{"id":"link-chainlink","name":"Chainlink","symbol":"LINK","rank":25,"total_supply":1000000000,"max_supply":0,"beta_value":1.58363,"first_data_at":"2017-09-20T00:00:00Z","last_updated":"2026-07-04T20:43:15Z","quotes":{"USD":{"price":8.046604107703255,"volume_24h":138422678.9938523,"volume_24h_change_24h":-25.360000610351562,"market_cap":5044013543,"market_cap_change_24h":1.1299999952316284,"percent_change_15m":0.17000000178813934,"percent_change_30m":-0.3400000035762787,"percent_change_1h":-0.25999999046325684,"percent_change_6h":0.

[{'id': 'btc-bitcoin',
  'name': 'Bitcoin',
  'symbol': 'BTC',
  'rank': 1,
  'total_supply': 20052166,
  'max_supply': 21000000,
  'beta_value': 0.971691,
  'first_data_at': '2010-07-17T00:00:00Z',
  'last_updated': '2026-07-04T20:43:15Z',
  'quotes': {'USD': {'price': 63196.947775148765,
    'volume_24h': 16790265688.53894,
    'volume_24h_change_24h': -26.690000534057617,
    'market_cap': 1267235687480,
    'market_cap_change_24h': 1.149999976158142,
    'percent_change_15m': 0.07999999821186066,
    'percent_change_30m': -0.10999999940395355,
    'percent_change_1h': -0.07999999821186066,
    'percent_change_6h': 0.9399999976158142,
    'percent_change_12h': 1.0800000429153442,
    'percent_change_24h': 1.149999976158142,
    'percent_change_7d': 4.989999771118164,
    'percent_change_30d': 0,
    'percent_change_1y': 0,
    'ath_price': 126173.1777846797,
    'ath_date': '2025-10-06T19:00:40Z',
    'percent_from_price_ath': -49.91}}},
 {'id': 'eth-ethereum',
  'name': 'Ethereum',
  'symbol': 'ETH',
  'rank': 2,
  'total_supply': 120232214,
  'max_supply': 0,
  'beta_value': 1.45069,
  'first_data_at': '2015-08-07T00:00:00Z',
  'last_updated': '2026-07-04T20:43:15Z',
  'quotes': {'USD': {'price': 1787.3090327303148,
    'volume_24h': 5781206580.846204,
    'volume_24h_change_24h': -18.729999542236328,
    'market_cap': 215239042365,
    'market_cap_change_24h': 1.7599999904632568,
    'percent_change_15m': 0.14000000059604645,
    'percent_change_30m': -0.27000001072883606,
    'percent_change_1h': -0.27000001072883606,
    'percent_change_6h': 1.0499999523162842,
    'percent_change_12h': 1.5499999523162842,
    'percent_change_24h': 1.7599999904632568,
    'percent_change_7d': 13.329999923706055,
    'percent_change_30d': 0,
    'percent_change_1y': 0,
    'ath_price': 4946.229669645212,
    'ath_date': '2025-08-24T19:24:38Z',
    'percent_from_price_ath': -63.88}}},
 {'id': 'usdt-tether',
  'name': 'Tether',
  'symbol': 'USDT',
  'rank': 3,
  'total_supply': 189750324523,
  'max_supply': 0,
  'beta_value': -0.00149119,
  'first_data_at': '2015-02-25T00:00:00Z',
  'last_updated': '2026-07-04T20:43:15Z',
  'quotes': {'USD': {'price': 0.9991413186529158,
    'volume_24h': 31598672580.20061,
    'volume_24h_change_24h': -28.739999771118164,
    'market_cap': 184125142085,
    'market_cap_change_24h': 0.019999999552965164,
    'percent_change_15m': -0.009999999776482582,
    'percent_change_30m': 0,
    'percent_change_1h': 0.009999999776482582,
    'percent_change_6h': 0,
    'percent_change_12h': 0.019999999552965164,
    'percent_change_24h': 0.019999999552965164,
    'percent_change_7d': 0.07000000029802322,
    'percent_change_30d': 0,
    'percent_change_1y': 0,
    'ath_price': 1.21549,
    'ath_date': '2015-02-25T17:04:00Z',
    'percent_from_price_ath': -17.8}}},
 {'id': 'bnb-binance-coin',
  'name': 'BNB',
  'symbol': 'BNB',
  'rank': 4,
  'total_supply': 134782677,
  'max_supply': 200000000,
  'beta_value': 1.04891,
  'first_data_at': '2017-07-25T00:00:00Z',
  'last_updated': '2026-07-04T20:43:15Z',
  'quotes': {'USD': {'price': 573.3980385824108,
    'volume_24h': 480878248.742317,
    'volume_24h_change_24h': -2.430000066757202,
    'market_cap': 77284122626,
    'market_cap_change_24h': 0.3100000023841858,
    'percent_change_15m': 0.05999999865889549,
    'percent_change_30m': -0.23000000417232513,
    'percent_change_1h': -0.36000001430511475,
    'percent_change_6h': -0.10000000149011612,
    'percent_change_12h': -0.25,
    'percent_change_24h': 0.3100000023841858,
    'percent_change_7d': 2.5999999046325684,
    'percent_change_30d': 0,
    'percent_change_1y': 0,
    'ath_price': 1370.9838437844724,
    'ath_date': '2025-10-13T09:00:44Z',
    'percent_from_price_ath': -58.19}}},
 {'id': 'usdc-usd-coin',
  'name': 'USDC',
  'symbol': 'USDC',
  'rank': 5,
  'total_supply': 72962441353,
  'max_supply': 0,
  'beta_value': -0.00346838,
  'first_data_at': '2018-10-09T00:00:00Z',
  'last_updated': '2026-07-04T20:43:15Z',
  'quotes': {'USD': {'price': 0.9998783832352426,
    'volume_24h': 7974366347.905231,
    'volume_24h_change_24h': -26.530000686645508,
    'market_cap': 72956117718,
    'market_cap_change_24h': -0.07000000029802322,
    'percent_change_15m': -0.009999999776482582,
    'percent_change_30m': 0,
    'percent_change_1h': 0.009999999776482582,
    'percent_change_6h': 0.009999999776482582,
    'percent_change_12h': 0.009999999776482582,
    'percent_change_24h': 0,
    'percent_change_7d': 0.009999999776482582,
    'percent_change_30d': 0,
    'percent_change_1y': 0,
    'ath_price': 1.90619801,
    'ath_date': '2018-10-11T06:35:00Z',
    'percent_from_price_ath': -47.55}}},
 {'id': 'xrp-xrp',
  'name': 'XRP',
  'symbol': 'XRP',
  'rank': 6,
  'total_supply': 99985645029,
  'max_supply': 100000000000,
  'beta_value': 1.31707,
  'first_data_at': '2013-08-04T00:00:00Z',
  'last_updated': '2026-07-04T20:43:15Z',
  'quotes': {'USD': {'price': 1.161274713674448,
    'volume_24h': 1465750084.5322864,
    'volume_24h_change_24h': 8.550000190734863,
    'market_cap': 72279490316,
    'market_cap_change_24h': 2.990000009536743,
    'percent_change_15m': 0.07999999821186066,
    'percent_change_30m': -0.5699999928474426,
    'percent_change_1h': -0.49000000953674316,
    'percent_change_6h': -0.9700000286102295,
    'percent_change_12h': 1.8300000429153442,
    'percent_change_24h': 2.990000009536743,
    'percent_change_7d': 10.399999618530273,
    'percent_change_30d': 0,
    'percent_change_1y': 0,
    'ath_price': 3.84194,
    'ath_date': '2018-01-04T07:14:00Z',
    'percent_from_price_ath': -69.77}}},
 {'id': 'sol-solana',
  'name': 'Solana',
  'symbol': 'SOL',
  'rank': 7,
  'total_supply': 588682058,
  'max_supply': 0,
  'beta_value': 1.55129,
  'first_data_at': '2020-08-26T00:00:00Z',
  'last_updated': '2026-07-04T20:43:15Z',
  'quotes': {'USD': {'price': 81.91409385643679,
    'volume_24h': 1605366587.2155302,
    'volume_24h_change_24h': -2.680000066757202,
    'market_cap': 47602784954,
    'market_cap_change_24h': -0.33000001311302185,
    'percent_change_15m': 0.18000000715255737,
    'percent_change_30m': 0.05999999865889549,
    'percent_change_1h': 0.17000000178813934,
    'percent_change_6h': 0.2800000011920929,
    'percent_change_12h': -0.3400000035762787,
    'percent_change_24h': -0.3499999940395355,
    'percent_change_7d': 15.270000457763672,
    'percent_change_30d': 0,
    'percent_change_1y': 0,
    'ath_price': 294.1631972172844,
    'ath_date': '2025-01-19T11:17:03Z',
    'percent_from_price_ath': -72.17}}},
 {'id': 'trx-tron',
  'name': 'TRON',
  'symbol': 'TRX',
  'rank': 8,
  'total_supply': 86363124686,
  'max_supply': 0,
  'beta_value': 0.311245,
  'first_data_at': '2017-09-13T00:00:00Z',
  'last_updated': '2026-07-04T20:43:15Z',
  'quotes': {'USD': {'price': 0.3259258382726382,
    'volume_24h': 340645039.3076443,
    'volume_24h_change_24h': -14.319999694824219,
    'market_cap': 28148030460,
    'market_cap_change_24h': 1.1200000047683716,
    'percent_change_15m': 0.03999999910593033,
    'percent_change_30m': -0.03999999910593033,
    'percent_change_1h': -0.009999999776482582,
    'percent_change_6h': 0.1899999976158142,
    'percent_change_12h': 0.6899999976158142,
    'percent_change_24h': 1.1200000047683716,
    'percent_change_7d': 1.6399999856948853,
    'percent_change_30d': 0,
    'percent_change_1y': 0,
    'ath_price': 0.4404408234447792,
    'ath_date': '2024-12-04T00:12:23Z',
    'percent_from_price_ath': -26.02}}},
 {'id': 'hype-hyperliquid',
  'name': 'Hyperliquid',
  'symbol': 'HYPE',
  'rank': 9,
  'total_supply': 999993930,
  'max_supply': 1000000000,
  'beta_value': 1.3612,
  'first_data_at': '2024-12-09T00:00:00Z',
  'last_updated': '2026-07-04T20:43:15Z',
  'quotes': {'USD': {'price': 69.85829703806039,
    'volume_24h': 197517856.27465457,
    'volume_24h_change_24h': -30.219999313354492,
    'market_cap': 23327653987,
    'market_cap_change_24h': -0.9800000190734863,
    'percent_change_15m': 0.27000001072883606,
    'percent_change_30m': 0.18000000715255737,
    'percent_change_1h': 0.11999999731779099,
    'percent_change_6h': -0.8999999761581421,
    'percent_change_12h': -1.690000057220459,
    'percent_change_24h': -0.9800000190734863,
    'percent_change_7d': 12.149999618530273,
    'percent_change_30d': 0,
    'percent_change_1y': 0,
    'ath_price': 76.76282696217518,
    'ath_date': '2026-06-16T13:01:19Z',
    'percent_from_price_ath': -8.98}}},
 {'id': 'steth-lido-staked-ether',
  'name': 'Lido Staked Ether',
  'symbol': 'STETH',
  'rank': 10,
  'total_supply': 9785853,
  'max_supply': 0,
  'beta_value': 1.45109,
  'first_data_at': '2021-08-12T00:00:00Z',
  'last_updated': '2026-07-04T20:43:15Z',
  'quotes': {'USD': {'price': 1791.421516529502,
    'volume_24h': 6364220.973839704,
    'volume_24h_change_24h': 28.34000015258789,
    'market_cap': 17545897110,
    'market_cap_change_24h': 2.009999990463257,
    'percent_change_15m': 0.11999999731779099,
    'percent_change_30m': -0.23999999463558197,
    'percent_change_1h': -0.03999999910593033,
    'percent_change_6h': 1.5099999904632568,
    'percent_change_12h': 1.7699999809265137,
    'percent_change_24h': 2.009999990463257,
    'percent_change_7d': 13.9399995803833,
    'percent_change_30d': 0,
    'percent_change_1y': 0,
    'ath_price': 4930.286952501686,
    'ath_date': '2025-08-24T19:24:38Z',
    'percent_from_price_ath': -63.69}}},
 {'id': 'doge-dogecoin',
  'name': 'Dogecoin',
  'symbol': 'DOGE',
  'rank': 11,
  'total_supply': 148311776384,
  'max_supply': 0,
  'beta_value': 1.55622,
  'first_data_at': '2013-12-15T00:00:00Z',
  'last_updated': '2026-07-04T20:43:15Z',
  'quotes': {'USD': {'price': 0.07806102619831293,
    'volume_24h': 512395120.5053966,
    'volume_24h_change_24h': -3.609999895095825,
    'market_cap': 11642622234,
    'market_cap_change_24h': 0.6600000262260437,
    'percent_change_15m': 0.05999999865889549,
    'percent_change_30m': -0.5799999833106995,
    'percent_change_1h': -0.6100000143051147,
    'percent_change_6h': 0.7400000095367432,
    'percent_change_12h': 1.5700000524520874,
    'percent_change_24h': 0.6600000262260437,
    'percent_change_7d': 4.760000228881836,
    'percent_change_30d': 0,
    'percent_change_1y': 0,
    'ath_price': 0.75287027,
    'ath_date': '2021-05-08T05:00:00Z',
    'percent_from_price_ath': -89.63}}},
 {'id': 'usds-usds',
  'name': 'Usds',
  'symbol': 'USDS',
  'rank': 12,
  'total_supply': 11077194156,
  'max_supply': 0,
  'beta_value': -0.0040967,
  'first_data_at': '2024-09-21T00:00:00Z',
  'last_updated': '2026-07-04T20:43:15Z',
  'quotes': {'USD': {'price': 0.9997782844308519,
    'volume_24h': 53950131.90850474,
    'volume_24h_change_24h': -52.09000015258789,
    'market_cap': 11074738169,
    'market_cap_change_24h': 0,
    'percent_change_15m': 0,
    'percent_change_30m': 0.009999999776482582,
    'percent_change_1h': 0.009999999776482582,
    'percent_change_6h': 0,
    'percent_change_12h': 0.009999999776482582,
    'percent_change_24h': 0,
    'percent_change_7d': 0.03999999910593033,
    'percent_change_30d': 0,
    'percent_change_1y': 0,
    'ath_price': 1.5820505120750166,
    'ath_date': '2024-09-24T03:00:21Z',
    'percent_from_price_ath': -36.8}}},
 {'id': 'leo-leo-token',
  'name': 'LEO Token',
  'symbol': 'LEO',
  'rank': 13,
  'total_supply': 985239504,
  'max_supply': 0,
  'beta_value': 0.255359,
  'first_data_at': '2019-05-20T00:00:00Z',
  'last_updated': '2026-07-04T20:43:15Z',
  'quotes': {'USD': {'price': 9.143799108706803,
    'volume_24h': 87923.61185242282,
    'volume_24h_change_24h': -70.20999908447266,
    'market_cap': 8420333795,
    'market_cap_change_24h': -0.14000000059604645,
    'percent_change_15m': -0.07000000029802322,
    'percent_change_30m': 0.019999999552965164,
    'percent_change_1h': -0.019999999552965164,
    'percent_change_6h': -0.20000000298023224,
    'percent_change_12h': -0.20999999344348907,
    'percent_change_24h': -0.14000000059604645,
    'percent_change_7d': -2.890000104904175,
    'percent_change_30d': 0,
    'percent_change_1y': 0,
    'ath_price': 10.45821201979332,
    'ath_date': '2026-04-29T01:22:16Z',
    'percent_from_price_ath': -12.52}}},
 {'id': 'wbtc-wrapped-bitcoin',
  'name': 'Wrapped Bitcoin',
  'symbol': 'WBTC',
  'rank': 14,
  'total_supply': 131178,
  'max_supply': 0,
  'beta_value': 0.970677,
  'first_data_at': '2019-01-31T00:00:00Z',
  'last_updated': '2026-07-04T20:43:15Z',
  'quotes': {'USD': {'price': 63191.49267025023,
    'volume_24h': 118424058.01568425,
    'volume_24h_change_24h': -10.15999984741211,
    'market_cap': 8289333625,
    'market_cap_change_24h': 1.1799999475479126,
    'percent_change_15m': 0.09000000357627869,
    'percent_change_30m': -0.10999999940395355,
    'percent_change_1h': -0.05999999865889549,
    'percent_change_6h': 0.949999988079071,
    'percent_change_12h': 1.090000033378601,
    'percent_change_24h': 1.1799999475479126,
    'percent_change_7d': 5.110000133514404,
    'percent_change_30d': 0,
    'percent_change_1y': 0,
    'ath_price': 126028.39561559023,
    'ath_date': '2025-10-06T19:03:39Z',
    'percent_from_price_ath': -49.87}}},
 {'id': 'wbt-whitebit',
  'name': 'WhiteBIT Coin',
  'symbol': 'WBT',
  'rank': 15,
  'total_supply': 369441188,
  'max_supply': 400000000,
  'beta_value': 0.706237,
  'first_data_at': '2022-08-26T00:00:00Z',
  'last_updated': '2026-07-04T20:43:15Z',
  'quotes': {'USD': {'price': 57.041114180341125,
    'volume_24h': 75666316.02673513,
    'volume_24h_change_24h': -19.34000015258789,
    'market_cap': 8220680783,
    'market_cap_change_24h': 0.9599999785423279,
    'percent_change_15m': 0.10999999940395355,
    'percent_change_30m': -0.14000000059604645,
    'percent_change_1h': -0.11999999731779099,
    'percent_change_6h': 0.8700000047683716,
    'percent_change_12h': 0.9100000262260437,
    'percent_change_24h': 0.9599999785423279,
    'percent_change_7d': 18.739999771118164,
    'percent_change_30d': 0,
    'percent_change_1y': 0,
    'ath_price': 64.48298634623086,
    'ath_date': '2025-12-10T20:19:16Z',
    'percent_from_price_ath': -11.54}}},
 {'id': 'wsteth-wrapped-liquid-staked-ether-20',
  'name': 'Wrapped Liquid Staked Ether 2.0',
  'symbol': 'WSTETH',
  'rank': 16,
  'total_supply': 3555731,
  'max_supply': 0,
  'beta_value': 1.45128,
  'first_data_at': '2022-06-08T00:00:00Z',
  'last_updated': '2026-07-04T20:43:15Z',
  'quotes': {'USD': {'price': 2212.5046183834884,
    'volume_24h': 3701477.5556296236,
    'volume_24h_change_24h': -8.829999923706055,
    'market_cap': 7867071259,
    'market_cap_change_24h': 1.7699999809265137,
    'percent_change_15m': 0.10000000149011612,
    'percent_change_30m': -0.3199999928474426,
    'percent_change_1h': -0.28999999165534973,
    'percent_change_6h': 1.059999942779541,
    'percent_change_12h': 1.6200000047683716,
    'percent_change_24h': 1.7699999809265137,
    'percent_change_7d': 13.34000015258789,
    'percent_change_30d': 0,
    'percent_change_1y': 0,
    'ath_price': 5979.080126100078,
    'ath_date': '2025-08-24T19:24:38Z',
    'percent_from_price_ath': -63}}},
 {'id': 'zec-zcash',
  'name': 'Zcash',
  'symbol': 'ZEC',
  'rank': 17,
  'total_supply': 16328269,
  'max_supply': 21000000,
  'beta_value': 1.7072,
  'first_data_at': '2016-10-29T00:00:00Z',
  'last_updated': '2026-07-04T20:43:15Z',
  'quotes': {'USD': {'price': 467.6266605898083,
    'volume_24h': 234849429.54142475,
    'volume_24h_change_24h': -42.130001068115234,
    'market_cap': 7635533905,
    'market_cap_change_24h': 0.8399999737739563,
    'percent_change_15m': 0.3400000035762787,
    'percent_change_30m': -0.09000000357627869,
    'percent_change_1h': -0.28999999165534973,
    'percent_change_6h': 0.6499999761581421,
    'percent_change_12h': 1.5299999713897705,
    'percent_change_24h': 0.8399999737739563,
    'percent_change_7d': 17.399999618530273,
    'percent_change_30d': 0,
    'percent_change_1y': 0,
    'ath_price': 5941.8,
    'ath_date': '2016-10-29T15:59:00Z',
    'percent_from_price_ath': -92.12}}},
 {'id': 'ada-cardano',
  'name': 'Cardano',
  'symbol': 'ADA',
  'rank': 18,
  'total_supply': 44995037804,
  'max_supply': 45000000000,
  'beta_value': 1.63183,
  'first_data_at': '2017-10-01T00:00:00Z',
  'last_updated': '2026-07-04T20:43:15Z',
  'quotes': {'USD': {'price': 0.1915808223313957,
    'volume_24h': 664007287.2587409,
    'volume_24h_change_24h': 7.699999809265137,
    'market_cap': 7420584893,
    'market_cap_change_24h': 7.230000019073486,
    'percent_change_15m': -0.009999999776482582,
    'percent_change_30m': -0.800000011920929,
    'percent_change_1h': -0.7900000214576721,
    'percent_change_6h': 5.019999980926514,
    'percent_change_12h': 8.930000305175781,
    'percent_change_24h': 7.199999809265137,
    'percent_change_7d': 32.34000015258789,
    'percent_change_30d': 0,
    'percent_change_1y': 0,
    'ath_price': 3.0950278974839334,
    'ath_date': '2021-09-02T06:00:00Z',
    'percent_from_price_ath': -93.81}}},
 {'id': 'xlm-stellar',
  'name': 'Stellar',
  'symbol': 'XLM',
  'rank': 19,
  'total_supply': 50001786840,
  'max_supply': 50001806812,
  'beta_value': 1.34376,
  'first_data_at': '2014-08-05T00:00:00Z',
  'last_updated': '2026-07-04T20:43:15Z',
  'quotes': {'USD': {'price': 0.20855426484176284,
    'volume_24h': 668331279.6701117,
    'volume_24h_change_24h': 188.5399932861328,
    'market_cap': 7089327682,
    'market_cap_change_24h': 2.319999933242798,
    'percent_change_15m': -0.009999999776482582,
    'percent_change_30m': -0.3799999952316284,
    'percent_change_1h': -0.5,
    'percent_change_6h': 1.3700000047683716,
    'percent_change_12h': 0.9300000071525574,
    'percent_change_24h': 2.319999933242798,
    'percent_change_7d': 19.799999237060547,
    'percent_change_30d': 0,
    'percent_change_1y': 0,
    'ath_price': 0.938144,
    'ath_date': '2018-01-04T08:19:00Z',
    'percent_from_price_ath': -77.74}}},
 {'id': 'weth-weth',
  'name': 'WETH',
  'symbol': 'WETH',
  'rank': 20,
  'total_supply': 3765896,
  'max_supply': 0,
  'beta_value': 1.44979,
  'first_data_at': '2018-01-14T00:00:00Z',
  'last_updated': '2026-07-04T20:43:15Z',
  'quotes': {'USD': {'price': 1786.551411006403,
    'volume_24h': 266220347.7730071,
    'volume_24h_change_24h': 6.230000019073486,
    'market_cap': 6727966812,
    'market_cap_change_24h': 1.7000000476837158,
    'percent_change_15m': 0.10000000149011612,
    'percent_change_30m': -0.3199999928474426,
    'percent_change_1h': -0.3199999928474426,
    'percent_change_6h': 1,
    'percent_change_12h': 1.5199999809265137,
    'percent_change_24h': 1.7000000476837158,
    'percent_change_7d': 13.300000190734863,
    'percent_change_30d': 0,
    'percent_change_1y': 0,
    'ath_price': 4944.739160754335,
    'ath_date': '2025-08-24T19:24:38Z',
    'percent_from_price_ath': -63.91}}},
 {'id': 'xmr-monero',
  'name': 'Monero',
  'symbol': 'XMR',
  'rank': 21,
  'total_supply': 18773624,
  'max_supply': 0,
  'beta_value': 0.836937,
  'first_data_at': '2014-05-21T00:00:00Z',
  'last_updated': '2026-07-04T20:43:15Z',
  'quotes': {'USD': {'price': 328.64792105104965,
    'volume_24h': 164281516.77758306,
    'volume_24h_change_24h': 20.280000686645508,
    'market_cap': 6169912169,
    'market_cap_change_24h': 1.440000057220459,
    'percent_change_15m': 0.15000000596046448,
    'percent_change_30m': 0.2800000011920929,
    'percent_change_1h': -0.07000000029802322,
    'percent_change_6h': -1.090000033378601,
    'percent_change_12h': -0.8500000238418579,
    'percent_change_24h': 1.4299999475479126,
    'percent_change_7d': 5.380000114440918,
    'percent_change_30d': 0,
    'percent_change_1y': 0,
    'ath_price': 797.1378386984193,
    'ath_date': '2026-01-14T19:34:17Z',
    'percent_from_price_ath': -58.76}}},
 {'id': 'usde-ethena-usde',
  'name': 'Ethena USDe',
  'symbol': 'USDE',
  'rank': 22,
  'total_supply': 5419558970,

In [45]:
crypto_data = response.json()

In [46]:
crypto_df = pd.DataFrame(crypto_data)

crypto_df.head()

,id,name,symbol,rank,total_supply,max_supply,beta_value,first_data_at,last_updated,quotes
0,btc-bitcoin,Bitcoin,BTC,1,20052166,21000000,0.971691,2010-07-17T00:00:00Z,2026-07-04T20:43:15Z,"{'USD': {'price': 63196.947775148765, 'volume_..."
1,eth-ethereum,Ethereum,ETH,2,120232214,0,1.450690,2015-08-07T00:00:00Z,2026-07-04T20:43:15Z,"{'USD': {'price': 1787.3090327303148, 'volume_..."
2,usdt-tether,Tether,USDT,3,189750324523,0,-0.001491,2015-02-25T00:00:00Z,2026-07-04T20:43:15Z,"{'USD': {'price': 0.9991413186529158, 'volume_..."
3,bnb-binance-coin,BNB,BNB,4,134782677,200000000,1.048910,2017-07-25T00:00:00Z,2026-07-04T20:43:15Z,"{'USD': {'price': 573.3980385824108, 'volume_2..."
4,usdc-usd-coin,USDC,USDC,5,72962441353,0,-0.003468,2018-10-09T00:00:00Z,2026-07-04T20:43:15Z,"{'USD': {'price': 0.9998783832352426, 'volume_..."

In [47]:
my_coins = ['btc-bitcoin', 'eth-ethereum', 'sol-solana', 'doge-dogecoin', 'usdt-tether']

coins_df = crypto_df[crypto_df['id'].isin(my_coins)].copy()

coins_df

,id,name,symbol,rank,total_supply,max_supply,beta_value,first_data_at,last_updated,quotes
0,btc-bitcoin,Bitcoin,BTC,1,20052166,21000000,0.971691,2010-07-17T00:00:00Z,2026-07-04T20:43:15Z,"{'USD': {'price': 63196.947775148765, 'volume_..."
1,eth-ethereum,Ethereum,ETH,2,120232214,0,1.450690,2015-08-07T00:00:00Z,2026-07-04T20:43:15Z,"{'USD': {'price': 1787.3090327303148, 'volume_..."
2,usdt-tether,Tether,USDT,3,189750324523,0,-0.001491,2015-02-25T00:00:00Z,2026-07-04T20:43:15Z,"{'USD': {'price': 0.9991413186529158, 'volume_..."
6,sol-solana,Solana,SOL,7,588682058,0,1.551290,2020-08-26T00:00:00Z,2026-07-04T20:43:15Z,"{'USD': {'price': 81.91409385643679, 'volume_2..."
10,doge-dogecoin,Dogecoin,DOGE,11,148311776384,0,1.556220,2013-12-15T00:00:00Z,2026-07-04T20:43:15Z,"{'USD': {'price': 0.07806102619831293, 'volume..."

In [ ]:
# Creating new columns and extracting the price, volume and market cap

coins_df['price'] = [row['USD']['price'] for row in coins_df['quotes']]

coins_df['volume'] = [row['USD']['volume_24h'] for row in coins_df['quotes']]

coins_df['market_cap'] = [row['USD']['market_cap'] for row in coins_df['quotes']]


coins_df[['id', 'name', 'price', 'volume', 'market_cap']]

               id      name         price        volume     market_cap
0     btc-bitcoin   Bitcoin  63196.947775  1.679027e+10  1267235687480
1    eth-ethereum  Ethereum   1787.309033  5.781207e+09   215239042365
2     usdt-tether    Tether      0.999141  3.159867e+10   184125142085
6      sol-solana    Solana     81.914094  1.605367e+09    47602784954
10  doge-dogecoin  Dogecoin      0.078061  5.123951e+08    11642622234

In [49]:
# Filter and clean columns

useful_columns = ['id', 'name', 'symbol', 'rank', 'price', 'volume', 'market_cap']

crypto_df = coins_df[useful_columns].copy()

crypto_df = crypto_df.rename(columns={'id': 'coin_id'})

crypto_df

,coin_id,name,symbol,rank,price,volume,market_cap
0,btc-bitcoin,Bitcoin,BTC,1,63196.947775,1.679027e+10,1267235687480
1,eth-ethereum,Ethereum,ETH,2,1787.309033,5.781207e+09,215239042365
2,usdt-tether,Tether,USDT,3,0.999141,3.159867e+10,184125142085
6,sol-solana,Solana,SOL,7,81.914094,1.605367e+09,47602784954
10,doge-dogecoin,Dogecoin,DOGE,11,0.078061,5.123951e+08,11642622234

In [50]:
# shows the currect UTC time
crypto_df['extracted_at'] = pd.Timestamp.now('UTC')

# shows how active the trading is relative to the coin's size
crypto_df['vol_to_market_cap_ratio'] = crypto_df['volume'] / crypto_df['market_cap']

crypto_df

,coin_id,name,symbol,rank,price,volume,market_cap,extracted_at,vol_to_market_cap_ratio
0,btc-bitcoin,Bitcoin,BTC,1,63196.947775,1.679027e+10,1267235687480,2026-07-04 20:45:41.855662+00:00,0.013250
1,eth-ethereum,Ethereum,ETH,2,1787.309033,5.781207e+09,215239042365,2026-07-04 20:45:41.855662+00:00,0.026859
2,usdt-tether,Tether,USDT,3,0.999141,3.159867e+10,184125142085,2026-07-04 20:45:41.855662+00:00,0.171615
6,sol-solana,Solana,SOL,7,81.914094,1.605367e+09,47602784954,2026-07-04 20:45:41.855662+00:00,0.033724
10,doge-dogecoin,Dogecoin,DOGE,11,0.078061,5.123951e+08,11642622234,2026-07-04 20:45:41.855662+00:00,0.044010

In [51]:
# store to db

DB_HOST = os.getenv('DB_HOST')
DB_PORT = os.getenv('DB_PORT')
DB_NAME = os.getenv('DB_NAME')
DB_USER = os.getenv('DB_USER')
DB_PASSWORD = os.getenv('DB_PASSWORD')

engine = create_engine(f'postgresql+psycopg2://{DB_USER}:{DB_PASSWORD}@{DB_HOST}:{DB_PORT}/{DB_NAME}')

crypto_df.to_sql('crypto_data', con=engine, if_exists='replace', index=False)

5